-record(db_group,{id, name, subgroups}).
-record(db_contact,{id, name="unknown", email="", phone, photo="undefined.png", bitmessage, address, my=false, status}).
-record(db_task,{id, due, name, text="", parent, status=new}).
-record(db_file,{id, path, type, user, date, status, size}).
-record(db_expense,{id, name, date, type=expense, text, amount, status, to, from}).
-record(db_update,{id, subject, from, to,  text, date, status}).
-record(db_contact_roles,{id, type, tid, role, contact}).
-record(db_attachment,{id, file, type, tid}).
-record(db_group_members, {group, contact}).
-record(db_expense_tasks, {expense, task}).
-record(db_task_tree, {task, parent, time, visible=false}).
-record(db_search, {text, id}).
