-record(group,{name, subgroups=[]}).
-record(contact,{name, email, phone, photo, address, groups=[]}).
-record(task,{id, due, name, text, linked=[]}).
-record(file,{id, path, type, user, date, status}).
-record(expense,{id, name, date, type, amount, status}).
-record(upd,{id, subject, from, text, date}).
-record(contact_roles,{id, type, tid, role, contct}).
-record(attachment,{id, file, type, tid}).
