-record(task_packet, {id, name, due, text, parent, status, involved, attachments, time}).
-record(role_packet, {address, role}).
-record(task_tree_packet, {task, parent}).
-record(message_packet, {subject, text, involved, attachments, time}).
